Elibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('library.urls')),
    path('library/', include('library.urls')),
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from accounts import views
from accounts.forms import LoginForm

urlpatterns = [
    path('login', LoginView.as_view(template_name='accounts/login.html', authentication_form=LoginForm), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', views.RegisterUser.as_view(), name='register_user'),
    path('', views.account, name='account'),
    path('settings', views.settings, name='settings'),
    path('change-password/<int:pk>', views.ChangePassword.as_view(), name='change_password'),
    path('update-email/<int:pk>', views.UpdateEmail.as_view(), name='update_email'),
    path('update-username/<int:pk>', views.UpdateUsername.as_view(), name='update_username'),
    path('delete-account/<int:pk>', views.DeleteAccount.as_view(), name='delete_account'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('queue/<int:pk>', views.QueueDetails.as_view(), name='queue_details'),
    path('queuelist', views.QueueList.as_view(), name='queue_list'),
    path('approve', views.approve_request, name='approve'),
    path('edit_book/<int:pk>', views.UpdateBook.as_view(), name='update_book'),
    path('delete_book/<int:pk>', views.DeleteBook.as_view(), name='delete_book'),
    path('my-books', views.BookList.as_view(), name='my-books'),
    path('update-profile/<int:pk>', views.UpdateProfile.as_view(), name='update_profile')
]

library/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('book/<int:pk>', views.BookDetails.as_view(), name='book_details'),
    path('addbook', views.AddBook.as_view(), name='add_book'),
    path('add-review', views.add_review, name='addreview'),
    path('all-books', views.BookList.as_view(), name='book_list'),
    path('borrow', views.borrow_page, name='borrow_page'),
    path('buy', views.buy_page, name='buy_page'),
    path('genre/<str:genre>', views.GenreList.as_view(), name='genre_list'),
    path('search', views.search, name='search'),

]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class UserAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # username, email, password, firstName, lastName
    address = models.CharField(max_length=500, null=True, blank=True)
    phone_number = models.CharField(max_length=11, null=True, blank=True)
    picture = models.ImageField(upload_to='users/images/', null=True, blank=True)
    biography = models.TextField(null=True, blank=True)

library/models.py
from django.db import models

# Create your models here.
from accounts.models import UserAccount


class Book(models.Model):
    name = models.CharField(max_length=200)
    about = models.TextField()
    illustrator = models.CharField(max_length=200)
    date_published = models.DateField()
    genre = models.CharField(max_length=200)
    publisher = models.CharField(max_length=200)
    book_image = models.ImageField(upload_to='books/images/')
    book_pdf = models.FileField(upload_to='books/pdfs', blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    book_type = models.CharField(max_length=200, choices=(
        ('Ebook', 'Ebook'),
        ('Printed book', 'Printed book'),
    ))
    author = models.CharField(max_length=200)
    books_we_love = models.BooleanField(null=True)
    book_category = models.CharField(max_length=200, choices=(
        ('For Sale', 'For Sale'),
        ('For Rent', 'For Rent'),
    ), null=True, blank=True)
    delivery_type = models.CharField(max_length=200, choices=(
        ('Meet at Mosque', 'Meet at Mosque'),
        ('Meet at Home', 'Meet at Home')
    ), null=True, blank=True)
    page_number = models.IntegerField()
    language = models.CharField(max_length=200)
    uploaded_by = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    is_available = models.BooleanField(null=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    review = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.book)

class BookRequested(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    date_requested = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

    class Meta:
        ordering = ['-date_requested']

class BookBorrowed(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    date_Borrowed = models.DateTimeField(auto_now_add=True)
    date_Returned = models.DateTimeField(auto_now_add=True)
    returned = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

    class Meta:
        ordering = ['-date_Borrowed']


class BookPurchased(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    date_Borrowed = models.DateTimeField(auto_now_add=True)
    date_Returned = models.DateTimeField(auto_now=True)
    returned = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from accounts.models import UserAccount


class UserAccountForm(forms.ModelForm):
    first_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(max_length=200, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = UserAccount
        fields = ('first_name', 'last_name', 'email', 'username', 'password', 'confirm_password')

    def save(self, commit=True):
        f = super(UserAccountForm, self).save(commit=False)
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        user = User.objects.create_user(username, email, password, first_name=first_name, last_name=last_name)
        f.user = user
        if commit:
            f.save()
        return f

    def clean_password(self):
        password = self.data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('Password must be at least 8 chars long', code='password')
        return password

    def clean_confirm_password(self):
        password = self.data.get('password')
        password2 = self.data.get('confirm_password')

        if password != password2:
            raise forms.ValidationError("Password fields must match", code='confirm_password')
        return password2


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from accounts.forms import UserAccountForm
from accounts.models import UserAccount
from library.forms import BookForm
from library.models import Book, BookBorrowed, BookRequested


class RegisterUser(CreateView):
    model = UserAccount
    form_class = UserAccountForm
    template_name = 'accounts/register_user.html'

    def get_success_url(self):
        messages.success(self.request, "You have successfully registered")
        return reverse('index')


def account(request):
    return render(request, 'accounts/index.html')


def settings(request):
    return render(request, 'accounts/settings.html')


# def changePassword(request):
#     return render(request, 'accounts/change_password.html')

class ChangePassword(UpdateView):
    model = User
    fields = ['password']
    template_name = 'accounts/change_password.html'

    def get_success_url(self):
        messages.success(self.request, "You have successfully changed your password")
        return reverse('profile', kwargs={'pk': int(self.request.user.pk)})


class UpdateEmail(UpdateView):
    model = User
    fields = ['email']
    template_name = 'accounts/update_email.html'

    def get_success_url(self):
        messages.success(self.request, "You have successfully updated your email")
        return reverse('profile', kwargs={'pk': int(self.request.user.pk)})


class UpdateUsername(UpdateView):
    model = User
    fields = ['username']
    template_name = 'accounts/update_username.html'

    def get_success_url(self):
        messages.success(self.request, "You have successfully updated your username")
        return reverse('profile', kwargs={'pk': int(self.request.user.pk)})


class DeleteAccount(DeleteView):
    model = UserAccount
    template_name = 'accounts/delete_account.html'
    success_url = reverse_lazy('index')


# def updateProfile(request):
#     return render(request, 'accounts/update_profile.html')

class UpdateProfile(UpdateView):
    model = UserAccount
    fields = ['address', 'phone_number', 'picture', 'biography']
    template_name = 'accounts/update_profile.html'

    def get_success_url(self):
        messages.success(self.request, "You have successfully updated your profile")
        return reverse('profile', kwargs={'pk': int(self.request.user.pk)})


def profile(request, pk):
    user = UserAccount.objects.get(pk=pk)
    all_books = user.book_set.all
    rented_books = Book.objects.filter(bookborrowed__user_id=user).distinct()
    purchased_books = Book.objects.filter(bookpurchased__user_id=user).distinct()
    context = {'user': user, 'allBooks': all_books, 'rented_books': rented_books,
               'purchased_books': purchased_books}
    return render(request, 'accounts/profile.html', context)


class QueueDetails(ListView):
    model = BookRequested
    template_name = 'accounts/queue_details.html'
    context_object_name = 'books'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(QueueDetails, self).get_context_data(**kwargs)
        user_books = Book.objects.filter(uploaded_by=self.request.user.useraccount)
        book = user_books.get(pk=self.kwargs.get('pk'))
        context['c'] = book.bookrequested_set.filter()
        context['book'] = book
        return context


class QueueList(ListView):
    model = BookRequested
    template_name = 'accounts/queue_list.html'
    context_object_name = 'books'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(QueueList, self).get_context_data(**kwargs)
        context['queuebooks'] = BookRequested.objects.filter(book__uploaded_by=self.request.user.useraccount)

        return context


def approve_request(request):
    book_pk = request.POST['book']
    user_pk = request.POST['user']
    book = Book.objects.get(pk=int(book_pk))
    user = UserAccount.objects.get(pk=int(user_pk))
    BookBorrowed.objects.create(book=book, user=user)
    BookRequested.objects.filter(user_id=int(user_pk), book_id=int(book_pk)).delete()
    send_mail(
        'Book granted',
        'Please ' + book.delivery_type + ' to get the book',
        'saliskamal@gmail.com',
        [book.uploaded_by.user.email, ],
        fail_silently=False,
    )
    messages.success(request, "Book approved")
    # context = {'user': user, 'book': book}
    return HttpResponseRedirect(reverse('profile', kwargs={'pk': int(request.user.pk)}))


class UpdateBook(UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'accounts/edit_book.html'

    def get_success_url(self):
        messages.success(self.request, "You have successfully updated")
        return reverse('index')


class DeleteBook(DeleteView):
    model = Book
    template_name = 'accounts/delete_book.html'
    success_url = reverse_lazy('my-books')


class BookList(ListView):
    model = Book
    template_name = 'accounts/my_books.html'
    context_object_name = 'books'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookList, self).get_context_data(**kwargs)
        # context['my_books'] = Book.objects.filter(book__uploaded_by=self.request.user.useraccount)
        context['my_books'] = self.request.user.useraccount.book_set.all

        return context

accounts/templates/accounts/change_password.html
{% extends 'base/layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link href="{% static 'assets/css/froala_style.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/froala_editor.pkgd.min.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Include external CSS. -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/awesomplete.css' %}">
    <script src="{% static 'assets/js/awesomplete.js' %}"></script>
{% endblock %}
{% block content %}
    {#<form method="post">{% csrf_token %}#}
    {#    {{ form.as_p }}#}
    {#    <input type="submit" value="Update">#}
    {#</form>#}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <br>
                    <h4 class="title text-center" style="color: #007bff;">Change Passsword</h4>
                </div>
                <div class="content">
                    <form id="page-form" method="post" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                        {#                    <div class="form-group">#}
                        {#                        <label for=""  class="control-label col-sm-2">Enter password</label>#}
                        {#                        <div  class="col-sm-8">#}
                        {#                            <input type="text" class="form-control" placeholder="Enter password">#}
                        {#                        </div>#}
                        {#                    </div>#}
                        {% for field in form %}
                            <div class="form-group" id="div_{{ field.name }}">
                                <label for="id_{{ field.name }}"
                                       class="control-label col-sm-2">{{ field.label }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors }}</p>
                                </div>
                            </div>
                        {% endfor %}
                        <div><p id="pdf_error"></p></div>
                        <div class="form-group">
                            <label class="control-label col-sm-2"></label>
                            <div class="col-sm-8">
                                <button class="btn btn-success" id="save" type="submit">Save</button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}
    <script>
        $('.errorlist li').addClass('text-danger');
    </script>
    {#    <script>#}
    {#        $('#id_uploaded_by').val({{ user }});#}
    {#    </script>#}

    <!-- Include external JS libs. -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>

    {#    <script#}
    {#            src="https://code.jquery.com/jquery-1.12.4.min.js"#}
    {#            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="#}
    {#            crossorigin="anonymous"></script>#}
    <script type="text/javascript" src="{% static 'assets/js/froala_editor.pkgd.min.js' %}"></script>

    <!-- Initialize the editor. -->
    <script>
        $(function () {
            $('textarea').froalaEditor();
            $('.form-group .col-sm-8 input').val('');
        });

        $('.form-group .col-sm-8 input').addClass('form-control');


        $('.form-group .col-sm-8 textarea').addClass('form-control');

        $('#picture-clear_id').hide();

    </script>

{% endblock %}

accounts/templates/accounts/delete_account.html
{% extends 'base/layout.html' %}
{% load static %}
{#<form method="post">{% csrf_token %}#}
{#    <p>Are you sure you want to delete "{{ object }}"?</p>#}
{#    <input type="submit" value="Confirm">#}
{#</form>#}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <br>
                    <h4 class="title text-center" style="color: #007bff;">Delete Account</h4>
                </div>
                <div class="card-body">
                    <form method="post">{% csrf_token %}
                        <div><p>Are you sure you want to delete your account ?</p></div>
                        <div class="form-group">
                            <label class="control-label col-sm-2"></label>
                            <div class="col-sm-8">
                                <button class="btn btn-success" type="submit">Confirm</button>
                            </div>
                        </div>
                        {#                        <input type="submit" value="Confirm">#}
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/edit_book.html
{% extends 'base/layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link href="{% static 'assets/css/froala_style.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/froala_editor.pkgd.min.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Include external CSS. -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/awesomplete.css' %}">
    <script src="{% static 'assets/js/awesomplete.js' %}"></script>
{% endblock %}
{% block content %}
    {#<form method="post">{% csrf_token %}#}
    {#    {{ form.as_p }}#}
    {#    <input type="submit" value="Update">#}
    {#</form>#}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <br>
                    <h4 class="title text-center" style="color: #007bff;">Edit Book</h4>
                </div>
                <div class="content">
                    <form id="page-form" method="post" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group" id="div_{{ field.name }}">
                                <label for="id_{{ field.name }}"
                                       class="control-label col-sm-2">{{ field.label }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors }}</p>
                                </div>
                            </div>
                        {% endfor %}
                        <div><p id="pdf_error"></p></div>
                        <div class="form-group">
                            <label class="control-label col-sm-2"></label>
                            <div class="col-sm-8">
                                <button class="btn btn-success" id="save" type="submit">Save</button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}
    <script>
        $('.errorlist li').addClass('text-danger');
    </script>
    {#    <script>#}
    {#        $('#id_uploaded_by').val({{ user }});#}
    {#    </script>#}

    <!-- Include external JS libs. -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>

    {#    <script#}
    {#            src="https://code.jquery.com/jquery-1.12.4.min.js"#}
    {#            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="#}
    {#            crossorigin="anonymous"></script>#}
    <script type="text/javascript" src="{% static 'assets/js/froala_editor.pkgd.min.js' %}"></script>

    <!-- Initialize the editor. -->
    <script>
        $(function () {
            $('textarea').froalaEditor();
        });



    </script>

{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends 'base/layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link href="{% static 'assets/css/froala_style.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/froala_editor.pkgd.min.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Include external CSS. -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/awesomplete.css' %}">
    <script src="{% static 'assets/js/awesomplete.js' %}"></script>
{% endblock %}
{% block content %}
    {#<form method="post">{% csrf_token %}#}
    {#    {{ form.as_p }}#}
    {#    <input type="submit" value="Update">#}
    {#</form>#}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <br>
                    <h4 class="title text-center" style="color: #007bff;">Update Profile</h4>
                </div>
                <div class="content">
                    <form id="page-form" method="post" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group" id="div_{{ field.name }}">
                                <label for="id_{{ field.name }}"
                                       class="control-label col-sm-2">{{ field.label }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors }}</p>
                                </div>
                            </div>
                        {% endfor %}
                        <div><p id="pdf_error"></p></div>
                        <div class="form-group">
                            <label class="control-label col-sm-2"></label>
                            <div class="col-sm-8">
                                <button class="btn btn-success" id="save" type="submit">Save</button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}
    <script>
        $('.errorlist li').addClass('text-danger');
    </script>
    {#    <script>#}
    {#        $('#id_uploaded_by').val({{ user }});#}
    {#    </script>#}

    <!-- Include external JS libs. -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>

    {#    <script#}
    {#            src="https://code.jquery.com/jquery-1.12.4.min.js"#}
    {#            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="#}
    {#            crossorigin="anonymous"></script>#}
    <script type="text/javascript" src="{% static 'assets/js/froala_editor.pkgd.min.js' %}"></script>

    <!-- Initialize the editor. -->
    <script>
        $(function () {
            $('textarea').froalaEditor();
        });

        $('.form-group .col-sm-8 input').addClass('form-control');
        $('.form-group .col-sm-8 textarea').addClass('form-control');

        $('#picture-clear_id').hide();

    </script>

{% endblock %}

accounts/templates/accounts/update_username.html
{% extends 'base/layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link href="{% static 'assets/css/froala_style.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/froala_editor.pkgd.min.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Include external CSS. -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/awesomplete.css' %}">
    <script src="{% static 'assets/js/awesomplete.js' %}"></script>
{% endblock %}
{% block content %}
    {#<form method="post">{% csrf_token %}#}
    {#    {{ form.as_p }}#}
    {#    <input type="submit" value="Update">#}
    {#</form>#}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <br>
                    <h4 class="title text-center" style="color: #007bff;">Update Username</h4>
                </div>
                <div class="content">
                    <form id="page-form" method="post" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
{#                    <div class="form-group">#}
{#                        <label for=""  class="control-label col-sm-2">Enter password</label>#}
{#                        <div  class="col-sm-8">#}
{#                            <input type="text" class="form-control" placeholder="Enter password">#}
{#                        </div>#}
{#                    </div>#}
                        {% for field in form %}
                            <div class="form-group" id="div_{{ field.name }}">
                                <label for="id_{{ field.name }}"
                                       class="control-label col-sm-2">{{ field.label }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors }}</p>
                                </div>
                            </div>
                        {% endfor %}
                        <div><p id="pdf_error"></p></div>
                        <div class="form-group">
                            <label class="control-label col-sm-2"></label>
                            <div class="col-sm-8">
                                <button class="btn btn-success" id="save" type="submit">Save</button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}
    <script>
        $('.errorlist li').addClass('text-danger');
    </script>
    {#    <script>#}
    {#        $('#id_uploaded_by').val({{ user }});#}
    {#    </script>#}

    <!-- Include external JS libs. -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>

    {#    <script#}
    {#            src="https://code.jquery.com/jquery-1.12.4.min.js"#}
    {#            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="#}
    {#            crossorigin="anonymous"></script>#}
    <script type="text/javascript" src="{% static 'assets/js/froala_editor.pkgd.min.js' %}"></script>

    <!-- Initialize the editor. -->
    <script>
        $(function () {
            $('textarea').froalaEditor();
        });

        $('.form-group .col-sm-8 input').addClass('form-control');
        $('.form-group .col-sm-8 textarea').addClass('form-control');

        $('#picture-clear_id').hide();

    </script>

{% endblock %}